/**
 * Peak Tools Hub — Complete Tool Registry v3
 * 41 tools with SEO metadata, FAQs, slugs
 */

export type ToolCategory = "finance" | "datetime" | "converters" | "daily" | "health" | "home";

export interface FAQ { q: string; a: string; }

export interface Tool {
  id: string; slug: string; name: string; desc: string; longDesc: string;
  icon: string; category: ToolCategory; keywords: string[];
  global: boolean; tag?: string; badge?: string;
  faq: FAQ[];
}

export const TOOLS: Tool[] = [
  { id:"salary", slug:"salary-calculator", name:"Salary Calculator", icon:"💼", category:"finance", global:true,
    desc:"Global net pay with pension, social security & income tax",
    longDesc:"Calculate exact net take-home pay across 19 countries: Malaysia (EPF/SOCSO/PCB), Singapore (CPF), UK (PAYE/NI), USA, Australia, India, Germany, Canada, Japan and more. All contribution rates 0–30% editable. Supports salary + bonus, resident/non-resident tax, and Zakat offset.",
    keywords:["salary calculator","net pay calculator","take home pay","epf calculator","cpf calculator","paye calculator","pcb calculator","global payroll","socso calculator","eis calculator"],
    faq:[
      {q:"How is net salary calculated?",a:"Net salary = Gross salary minus all mandatory deductions: income tax withholding, employee pension contributions, social security, and any additional funds like EIS or Zakat."},
      {q:"What is the EPF contribution rate in Malaysia?",a:"EPF employee rate is 11% of gross salary. Employer contributes 13% for wages ≤ RM5,000 and 12% above."},
      {q:"What is CPF rate in Singapore?",a:"CPF employee rate is 20% for those under 55. Employer contributes 17%. Rates decrease progressively with age."},
      {q:"What is the US Social Security tax rate?",a:"US Social Security is 6.2% for employees, matched 6.2% by employers up to the annual wage base. Medicare adds 1.45% each."},
      {q:"How is UK take-home pay calculated?",a:"UK take-home = Gross minus PAYE income tax, National Insurance (8% employee), and pension. Personal allowance is £12,570/year."},
      {q:"Can I change contribution rates?",a:"Yes. All pension, social security, EIS and additional fund rates are fully editable from 0% to 30%, letting you model any country or custom scenario."},
      {q:"What is Zakat on income?",a:"Zakat Pendapatan is 2.5% of annual income for eligible Muslims earning above the Nisab threshold (~RM22,600/year). It can offset PCB tax payable in Malaysia."},
      {q:"What is EIS?",a:"EIS (Employment Insurance System) provides income replacement if you lose your job. Both employee and employer each contribute 0.2%, capped at RM4,000 wages."},
      {q:"What is SOCSO?",a:"SOCSO provides employment injury and invalidity protection. Employee contributes 0.5% of wages, capped at RM4,000 monthly salary."},
      {q:"What is PCB in a Malaysian payslip?",a:"PCB (Potongan Cukai Berjadual) is the monthly tax withholding deducted by employers under LHDN's progressive tax schedule, ranging from 1% to 24.5%."},
    ]
  },
  { id:"loan", slug:"loan-calculator", name:"Loan & Mortgage Calculator", icon:"🏠", category:"finance", global:true,
    desc:"Monthly repayment, total interest & amortization schedule",
    longDesc:"Calculate monthly loan repayments, total interest, and full amortization schedule. Supports home loans, mortgages, car loans and personal loans worldwide with any currency.",
    keywords:["loan calculator","mortgage calculator","monthly repayment","home loan calculator","car loan calculator","amortization calculator"],
    faq:[
      {q:"How is a mortgage payment calculated?",a:"Monthly payment = P × r(1+r)^n / ((1+r)^n−1), where P is the loan amount, r is the monthly interest rate, and n is the total number of payments."},
      {q:"What is amortization?",a:"Amortization is paying off a loan through regular payments. Early payments are mostly interest; later payments are mostly principal as the balance decreases."},
      {q:"What is a good home loan interest rate?",a:"In Malaysia, home loan rates are typically 3.5–5% p.a. In the US, 30-year fixed rates have ranged from 3–8% in recent years."},
      {q:"How does loan term affect total interest?",a:"A longer term reduces monthly payments but significantly increases total interest paid. A 30-year loan at 5% typically pays over double the principal in total interest."},
      {q:"What is flat rate vs reducing balance?",a:"Flat rate charges interest on the original principal throughout. Reducing balance only charges on outstanding balance — resulting in lower total interest."},
      {q:"How much loan can I afford?",a:"A common guideline: total debt repayments should not exceed 35–40% of gross monthly income. Malaysian banks use DSR (Debt Service Ratio) to assess affordability."},
      {q:"What happens if I make extra payments?",a:"Extra principal payments reduce your outstanding balance, lower future interest charges, and can shorten your loan term significantly."},
      {q:"What is LTV (Loan-to-Value)?",a:"LTV = loan amount ÷ property value. Malaysian banks typically lend up to 90% LTV for the first two properties, 70% for the third."},
      {q:"What is a fixed vs variable rate loan?",a:"Fixed rate loans have a constant interest rate. Variable rates fluctuate with market benchmarks like OPR in Malaysia or SOFR in the US."},
      {q:"How is car loan interest calculated in Malaysia?",a:"Car loans in Malaysia typically use the flat rate method. Total interest = principal × flat rate × years. Monthly = (principal + total interest) ÷ months."},
    ]
  },
  { id:"compound", slug:"compound-interest-calculator", name:"Compound Interest Calculator", icon:"📈", category:"finance", global:true,
    desc:"Investment growth with monthly contributions over time",
    longDesc:"Visualise compound interest growth with custom returns, monthly contributions, and compounding frequencies. Ideal for ETF, unit trust, CPF, ASB, and retirement planning.",
    keywords:["compound interest calculator","investment calculator","future value calculator","savings calculator","retirement calculator"],
    faq:[
      {q:"What is compound interest?",a:"Compound interest is earned on both the principal and previously accumulated interest, causing exponential growth — unlike simple interest which only earns on the principal."},
      {q:"What is the Rule of 72?",a:"Divide 72 by the annual return rate to estimate how many years to double an investment. At 8% p.a., an investment doubles in approximately 9 years."},
      {q:"What is CAGR?",a:"CAGR (Compound Annual Growth Rate) is the rate at which an investment grows from start to end value, as if growing at a steady annual rate."},
      {q:"How do monthly contributions affect growth?",a:"Regular contributions dramatically amplify compound growth. Adding RM500/month to a RM10,000 investment at 8% for 20 years grows to over RM320,000 vs RM46,600 without contributions."},
      {q:"What return should I expect from unit trusts?",a:"Malaysian equity unit trusts have historically returned 6–12% p.a. over long periods. Past performance doesn't guarantee future results."},
      {q:"How does inflation affect investment returns?",a:"Real return = nominal return minus inflation. At 8% return and 3% inflation, your real purchasing power only grows at 5%."},
      {q:"Is compound interest better than simple interest?",a:"Yes. Compound interest grows exponentially while simple interest grows linearly. The difference becomes dramatic over 20+ years."},
      {q:"What is ROI vs CAGR?",a:"ROI is the total percentage gain. CAGR annualises it. A 100% ROI over 10 years equals a CAGR of approximately 7.2%."},
      {q:"What investments use compound interest?",a:"Fixed deposits, savings accounts, unit trusts, ETFs, bonds, ASB and most investment vehicles compound returns. The frequency varies by product."},
      {q:"How often should interest compound?",a:"More frequent compounding = greater returns. Daily > monthly > annual. Most investment funds compound monthly or annually."},
    ]
  },
  { id:"income-tax", slug:"income-tax-calculator", name:"Income Tax Calculator", icon:"🧾", category:"finance", global:true,
    desc:"Annual income tax with deductions and reliefs",
    longDesc:"Estimate annual income tax across Malaysia, Singapore, UK, USA, Australia, and India. Progressive tax bands with deductions and reliefs. Effective tax rate calculated.",
    keywords:["income tax calculator","tax calculator","paye tax","lhdn tax","iras tax","ato tax calculator"],
    faq:[
      {q:"How is income tax calculated?",a:"Income tax is calculated on your chargeable income (gross income minus approved deductions and reliefs) using progressive tax rate bands."},
      {q:"What are the income tax rates in Malaysia?",a:"Malaysia's resident personal tax rates range from 0% (income below RM5,000) to 24.5% (income above RM1,000,000)."},
      {q:"What reliefs can I claim in Malaysia?",a:"Common reliefs: personal (RM9,000), EPF (RM4,000), life insurance (RM3,000), medical expenses (RM8,000), education (RM7,000), SSPN (RM8,000)."},
      {q:"What is the difference between tax relief and tax rebate?",a:"Tax relief reduces your chargeable income (the amount taxed). Tax rebate directly reduces the tax payable after tax is calculated."},
      {q:"What is the tax filing deadline in Malaysia?",a:"Malaysian residents must file Form BE by April 30. E-filing via MyTax portal extends the deadline to May 15."},
      {q:"Who needs to file income tax in Malaysia?",a:"Any resident with annual income above RM34,000 after EPF deduction must file, including employment, business, and rental income."},
      {q:"What is tax residency in Malaysia?",a:"You are a Malaysian tax resident if you reside in Malaysia for 182 days or more in a calendar year, qualifying for progressive rates and reliefs."},
      {q:"What is the difference between PCB and actual tax?",a:"PCB is an estimate withheld monthly. Actual tax is calculated at annual filing. If PCB exceeded actual tax you get a refund; if less, you pay the difference."},
      {q:"What is e-Filing in Malaysia?",a:"e-Filing (e-BE) is LHDN's online platform available from March 1 each year. It provides a 15-day extension over the paper deadline."},
      {q:"What are the US federal income tax brackets?",a:"US 2024 brackets (single): 10% up to $11,600; 12% up to $47,150; 22% up to $100,525; 24% up to $191,950; 32% up to $243,725; 35% up to $609,350; 37% above."},
    ]
  },
  { id:"credit-card", slug:"credit-card-interest-calculator", name:"Credit Card Interest Calculator", icon:"💳", category:"finance", global:true,
    desc:"Balance payoff timeline, total interest & minimum payment warning",
    longDesc:"See exactly how long it takes to pay off a credit card and total interest at any monthly payment. Shows true cost of carrying a balance and minimum payment danger.",
    keywords:["credit card calculator","credit card interest","payoff calculator","debt calculator","APR calculator"],
    faq:[
      {q:"How is credit card interest calculated?",a:"Credit card interest = Outstanding balance × (APR ÷ 365) × days. Most cards compound daily. A RM5,000 balance at 18% APR accrues about RM2.47 in interest per day."},
      {q:"What is the minimum payment on a credit card?",a:"Minimum payment is typically 5% of outstanding balance or RM50 (whichever is higher) in Malaysia. Paying only minimum dramatically extends payoff time."},
      {q:"What is credit card APR?",a:"APR (Annual Percentage Rate) is the yearly interest rate on unpaid balances. In Malaysia, Bank Negara caps credit card rates at 18% p.a. for timely payers."},
      {q:"How long to pay off a credit card?",a:"At minimum payment on a RM5,000 balance at 18% APR, it takes over 10 years and costs RM3,000+ in interest. Use this calculator to find your payoff date."},
      {q:"What is the avalanche vs snowball debt method?",a:"Avalanche: pay off highest-interest debt first (mathematically optimal). Snowball: pay off smallest balance first (psychologically motivating). Avalanche saves more money."},
      {q:"What is a balance transfer?",a:"A balance transfer moves your debt to a new card offering 0% interest for a promotional period (typically 6–24 months), helping you pay down principal faster."},
      {q:"What is credit utilisation ratio?",a:"Credit utilisation = Total credit used ÷ Total credit limit × 100%. Keeping utilisation below 30% is recommended for a healthy credit score."},
      {q:"How do I avoid credit card interest?",a:"Pay the full statement balance by the due date each month. This gives you an interest-free period (typically 20–50 days) with no interest charged."},
      {q:"What is cashback vs rewards credit card?",a:"Cashback cards return a percentage of spending as cash (1–5%). Rewards cards give points redeemable for travel, merchandise or vouchers."},
      {q:"What is the late payment penalty in Malaysia?",a:"In Malaysia, late payment charges are capped at 1% of outstanding balance per month or RM10 minimum, plus the standard 18% APR continues to accrue."},
    ]
  },
  { id:"inflation", slug:"inflation-calculator", name:"Inflation Calculator", icon:"📉", category:"finance", global:true,
    desc:"Real purchasing power & value of money over time",
    longDesc:"Calculate how inflation erodes purchasing power over any time period at any rate. Project future values for retirement and long-term financial planning.",
    keywords:["inflation calculator","purchasing power calculator","real value calculator","CPI calculator"],
    faq:[
      {q:"What is inflation?",a:"Inflation is the rate at which the general level of prices rises over time, eroding the purchasing power of money."},
      {q:"How is inflation calculated?",a:"Inflation is measured using a Consumer Price Index (CPI), tracking price changes of a basket of commonly purchased goods and services."},
      {q:"What is Malaysia's average inflation rate?",a:"Malaysia's average CPI inflation has been 2–4% annually over the past decade, with higher readings in 2022–2023 due to global supply chain disruptions."},
      {q:"How does inflation affect savings?",a:"If your savings earn 2% interest but inflation is 4%, your real purchasing power decreases 2% each year — your money buys less even as the balance grows."},
      {q:"What is the rule of 70 for inflation?",a:"Divide 70 by the inflation rate to estimate years for prices to double. At 3.5% inflation, prices double in approximately 20 years."},
      {q:"What is hyperinflation?",a:"Hyperinflation is typically defined as over 50% per month. Historical examples include Zimbabwe (2008) and Germany (1923)."},
      {q:"How does the central bank control inflation?",a:"Central banks raise interest rates to reduce borrowing and spending, which slows economic demand and moderates price increases."},
      {q:"What is real vs nominal value?",a:"Nominal value is the face value of money. Real value adjusts for inflation to reflect true purchasing power."},
      {q:"What inflation rate should I use for projections?",a:"Use 3–4% for general expenses. Use 5–7% for healthcare and education costs, which typically inflate faster than general CPI."},
      {q:"How does inflation affect retirement planning?",a:"RM1,000,000 today at 3% inflation will only have the purchasing power of RM552,000 in 20 years. All retirement projections must account for inflation."},
    ]
  },
  { id:"profit-margin", slug:"profit-margin-calculator", name:"Profit Margin Calculator", icon:"💰", category:"finance", global:true,
    desc:"Revenue, cost, gross margin & markup analysis",
    longDesc:"Calculate gross profit margin and markup from revenue and cost. Essential for pricing strategy, business planning, and financial analysis across all currencies.",
    keywords:["profit margin calculator","gross margin calculator","markup calculator","profit calculator"],
    faq:[
      {q:"What is gross profit margin?",a:"Gross profit margin = (Revenue − Cost) / Revenue × 100. It shows how efficiently a company produces products after direct costs."},
      {q:"What is the difference between margin and markup?",a:"Margin = Profit / Revenue × 100. Markup = Profit / Cost × 100. A 50% markup equals a 33.3% margin. Markup is always higher than margin for the same profit."},
      {q:"What is a good profit margin by industry?",a:"Software/SaaS: 70–90%. Retail: 2–5%. Restaurants: 3–9%. Manufacturing: 5–20%. Professional services: 20–40%. Margins vary widely by sector."},
      {q:"How do I calculate net profit margin?",a:"Net profit margin = Net Profit (after all expenses, tax, interest) / Revenue × 100. This calculator focuses on gross margin."},
      {q:"What is contribution margin?",a:"Contribution margin = Revenue − Variable Costs. It shows how much each sale contributes to covering fixed costs and generating profit."},
      {q:"How do I improve profit margin?",a:"Increase prices (if market allows), reduce COGS through better sourcing, improve operational efficiency, and reduce overheads."},
      {q:"What is EBITDA?",a:"EBITDA = Earnings Before Interest, Tax, Depreciation and Amortisation. It measures core operating profitability, removing non-cash items."},
      {q:"What is break-even point?",a:"Break-even = Fixed Costs / (Price per unit − Variable Cost per unit). At this point, total revenue equals total costs and profit is zero."},
      {q:"How is markup different from margin?",a:"A 25% margin on RM100 revenue = RM25 profit. A 25% markup on RM75 cost = RM18.75 profit. Markup is calculated from cost; margin from revenue."},
      {q:"What is a healthy gross margin for an SME?",a:"For most SMEs, a gross margin above 40% is healthy. Below 20% leaves little room after overheads. Service businesses typically achieve higher margins than product businesses."},
    ]
  },
  { id:"zakat", slug:"zakat-calculator-malaysia", name:"Zakat Calculator", icon:"☪️", category:"finance", global:false, tag:"MY",
    desc:"Zakat on savings, income, gold & business assets",
    longDesc:"Calculate Zakat obligations per JAKIM guidelines: income, savings, gold, and business assets. Includes 2025 Nisab threshold for Malaysia.",
    keywords:["zakat calculator malaysia","zakat pendapatan","kalkulator zakat","zakat simpanan","zakat emas"],
    faq:[
      {q:"What is Zakat?",a:"Zakat is one of the Five Pillars of Islam — an obligatory annual payment of 2.5% on qualifying assets for Muslims whose wealth exceeds the Nisab threshold."},
      {q:"What is Nisab in 2025?",a:"Nisab equals the value of 85 grams of gold (~RM22,000–RM25,000 in 2025, varying with gold prices)."},
      {q:"What is Zakat on income?",a:"Zakat Pendapatan is 2.5% of annual employment income for Muslims earning above the Nisab. It may be paid monthly at 2.5% of monthly income."},
      {q:"What is Haul in Zakat?",a:"Haul is the condition that wealth must have been held for one complete lunar year (354 days) before Zakat becomes due on it."},
      {q:"Can Zakat offset income tax in Malaysia?",a:"Yes. Zakat paid to a state Zakat authority can be deducted from assessed income tax (PCB) ringgit-for-ringgit, up to the full tax amount payable."},
      {q:"What types of wealth are Zakat-liable?",a:"Gold and silver, savings and investments, business stock and profits, agriculture produce, livestock, and employment income (Zakat Pendapatan)."},
      {q:"What is Zakat Fitrah?",a:"Zakat Fitrah is a fixed annual payment per person during Ramadan. In 2024, it is RM7 per person in most Malaysian states."},
      {q:"Where do I pay Zakat in Malaysia?",a:"Zakat is administered by state Islamic religious councils. Online payment is available via Lembaga Zakat Selangor, MAIWP, and other state bodies."},
      {q:"Is Zakat on EPF savings required?",a:"There are differing scholarly opinions. Some state authorities require Zakat on EPF savings above Nisab if held for one year; others exempt it until withdrawal."},
      {q:"What is Zakat on gold?",a:"Gold jewellery above 85g of gold content is subject to 2.5% Zakat after holding for one year, based on current market value of the gold."},
    ]
  },
  { id:"sst", slug:"sst-calculator-malaysia", name:"SST Calculator", icon:"🧮", category:"finance", global:false, tag:"MY",
    desc:"Malaysia Sales & Service Tax — 6%, 8% and 10% rates",
    longDesc:"Calculate Malaysia SST: Service Tax 8% (most services from March 2024), 6% (F&B/telco), Sales Tax 5% or 10% on goods. Inclusive and exclusive calculation.",
    keywords:["sst calculator malaysia","service tax calculator","sales tax malaysia","sst 8 percent","malaysia tax"],
    faq:[
      {q:"What is SST in Malaysia?",a:"SST (Sales and Service Tax) replaced GST in September 2018. Service Tax applies to B2B taxable services; Sales Tax applies to manufactured and imported goods."},
      {q:"What is the Service Tax rate in 2024?",a:"From March 1, 2024, Service Tax increased from 6% to 8% for most services. F&B and telecommunications services remain at 6%."},
      {q:"What is the Sales Tax rate?",a:"Sales Tax applies at 5% (basic necessities) or 10% (most other goods). Some goods are exempt or zero-rated."},
      {q:"What services are subject to 8% Service Tax?",a:"Professional services, IT services, management services, accounting, legal, advertising, and most B2B services attract 8% Service Tax."},
      {q:"What services remain at 6% Service Tax?",a:"Food and beverages, telecommunications services, and some other essential services remain at 6% after the 2024 increase."},
      {q:"Is SST charged on food in Malaysia?",a:"Service Tax of 6% applies at food service establishments with annual turnover above RM1.5 million. Most hawker stalls and food courts do not charge SST."},
      {q:"How is SST different from GST?",a:"GST was a broad 6% consumption tax on all goods and services. SST is narrower, with Sales Tax at manufacture/import and Service Tax on specific services."},
      {q:"Do I need to register for SST?",a:"Service Tax registration is required if taxable service revenue exceeds RM500,000/year. Sales Tax threshold is RM500,000 in annual sales."},
      {q:"How do I calculate price inclusive of SST?",a:"Price before SST = Inclusive Price / 1.06 (for 6%) or / 1.08 (for 8%). SST amount = Inclusive Price − Price before SST."},
      {q:"What is SST on imported goods?",a:"Imported goods are subject to Sales Tax at customs clearance. The applicable rate (5% or 10%) depends on the HS code classification."},
    ]
  },
  { id:"ptptn", slug:"ptptn-calculator", name:"PTPTN Loan Calculator", icon:"🎓", category:"finance", global:false, tag:"MY",
    desc:"PTPTN study loan repayment at 1% p.a. service charge",
    longDesc:"Calculate PTPTN monthly repayments, total interest, and repayment schedule at the standard 1% per annum service charge. Plan early settlement savings.",
    keywords:["ptptn calculator","ptptn repayment","pinjaman ptptn","ptptn monthly payment"],
    faq:[
      {q:"What is PTPTN?",a:"PTPTN (Perbadanan Tabung Pendidikan Tinggi Nasional) is Malaysia's national higher education fund providing study loans to Malaysian students."},
      {q:"What is the PTPTN interest rate?",a:"PTPTN charges a service charge of 1% per annum on the outstanding loan balance — one of the lowest study loan rates available."},
      {q:"When do I start repaying PTPTN?",a:"Repayment begins 12 months after graduating or leaving the institution, regardless of employment status."},
      {q:"How much PTPTN discount for early settlement?",a:"Full early settlement receives a 10% discount on outstanding balance. Consistent monthly repayment qualifies for a 20% discount on early settlement."},
      {q:"What happens if I don't repay PTPTN?",a:"PTPTN can take legal action, blacklist borrowers from renewing passports, and report to credit agencies."},
      {q:"Can I defer PTPTN payments?",a:"Yes. PTPTN offers deferment for borrowers facing genuine financial hardship, unemployment, or continuing postgraduate studies."},
      {q:"What is the maximum PTPTN loan amount?",a:"Public university students typically receive RM7,500–RM20,000/year. Private universities may receive more depending on programme and institution."},
      {q:"Does PTPTN cover full tuition?",a:"PTPTN covers tuition fees and living allowances but may not cover full costs at private institutions. Top students may receive full loans (pinjaman penuh)."},
      {q:"How do I check my PTPTN balance?",a:"Log in to ptptn.gov.my with your MyKad number to view outstanding balance, repayment history, and monthly installment amount."},
      {q:"What is SSPN?",a:"SSPN (Skim Simpanan Pendidikan Nasional) is PTPTN's education savings scheme. Deposits earn dividends and qualify for up to RM12,000/year income tax relief."},
    ]
  },
  { id:"age", slug:"age-calculator", name:"Age Calculator", icon:"🎂", category:"datetime", global:true,
    desc:"Exact age in years, months, days, weeks and total days",
    longDesc:"Calculate exact age from any date of birth. Shows years, months, days, total days and weeks. Handles leap years. Used for official documents and insurance.",
    keywords:["age calculator","how old am i","exact age calculator","date of birth calculator","birthday calculator"],
    faq:[
      {q:"How is exact age calculated?",a:"Exact age is counted in complete years, then remaining months, then remaining days from the date of birth to today, accounting for varying month lengths."},
      {q:"How many days old am I?",a:"Total days = days between your date of birth and today. This calculator shows days, weeks, months, and years simultaneously."},
      {q:"Does the age calculator account for leap years?",a:"Yes. The calculator uses JavaScript's Date object which correctly handles all leap years, ensuring accurate day counts across decades."},
      {q:"What is the legal age of majority globally?",a:"18 in most countries, 19 in South Korea and some US states, 20 in Japan, and 21 in some countries."},
      {q:"How do I calculate my age in months?",a:"Total months = (years × 12) + remaining months. This calculator shows both the breakdown and total months."},
      {q:"How is age calculated for newborns?",a:"For babies under 2 years, age is expressed in months and days. This calculator shows all units, making it suitable for tracking infant milestones."},
      {q:"Can I calculate someone else's age?",a:"Yes. Enter any date of birth and the calculator will compute the exact age of any person from that date to today."},
      {q:"How is retirement age calculated?",a:"Enter your date of birth and your country's retirement age (60 in Malaysia, 65–67 in UK/US) to find how many years remain."},
      {q:"What is chronological age vs biological age?",a:"Chronological age is the time since birth (what this calculator measures). Biological age reflects your body's actual cellular ageing."},
      {q:"How many weeks old am I?",a:"Total weeks = total days ÷ 7. For a person born January 1, 1990, that's approximately 1,826 weeks as of 2025."},
    ]
  },
  { id:"date-diff", slug:"date-difference-calculator", name:"Date Difference Calculator", icon:"📅", category:"datetime", global:true,
    desc:"Days, weeks, months & years between any two dates",
    longDesc:"Find the exact difference between any two dates in days, weeks, months and years. For project timelines, contracts, and date arithmetic.",
    keywords:["date difference calculator","days between dates","how many days between","date calculator"],
    faq:[
      {q:"How are days between dates calculated?",a:"The calculator finds the absolute difference in milliseconds between two dates and converts to days, weeks, months, and years."},
      {q:"Does it account for leap years?",a:"Yes. JavaScript's Date object correctly handles leap years, ensuring accurate day counts even across February 29th boundaries."},
      {q:"How are months calculated between dates?",a:"Months are approximated as days divided by 30.44 (average days per month)."},
      {q:"Can I calculate past and future dates?",a:"Yes. The calculator handles any direction — past to present, present to future, or any two dates regardless of order."},
      {q:"How do I count working days between dates?",a:"Use the Working Days Calculator on this site, which counts only Monday–Friday between any two dates."},
      {q:"How many weeks are in a year?",a:"A standard year has 52 weeks and 1 day (365 days). A leap year has 52 weeks and 2 days."},
      {q:"How many days until Christmas?",a:"Use the Countdown Timer on this site to get a live countdown to Christmas (December 25) or any other date."},
      {q:"What is the difference between calendar days and working days?",a:"Calendar days count all 7 days per week. Working days count only Monday–Friday. Contract terms often specify which applies."},
      {q:"How do I calculate project duration?",a:"Enter your project start and end dates. The calculator returns exact duration in days, weeks, months, and years."},
      {q:"Can I calculate age from a date?",a:"Use the Age Calculator for precise age with years, months and days. This tool is better for arbitrary date spans like project durations."},
    ]
  },
  { id:"working-days", slug:"working-days-calculator", name:"Working Days Calculator", icon:"📆", category:"datetime", global:true,
    desc:"Count Mon–Fri business days between any two dates",
    longDesc:"Count working days (Monday–Friday) between two dates. For project planning, SLA tracking, notice periods and payroll.",
    keywords:["working days calculator","business days calculator","weekdays between dates","workday counter"],
    faq:[
      {q:"What counts as a working day?",a:"Working days are Monday to Friday, excluding Saturday and Sunday. This calculator counts only Mon–Fri."},
      {q:"Are public holidays excluded?",a:"This calculator excludes weekends. For public holiday deduction, use it alongside the Public Holiday Calendar tool on this site."},
      {q:"How many working days are in a month?",a:"Typically 20–23 working days per month (4–5 weeks × 5 days). February has the fewest; months with 31 days may have 23."},
      {q:"How many working days in a year?",a:"A standard year has 260–262 working days. Public holidays reduce this to typically 240–250 depending on country."},
      {q:"What is SLA calculation?",a:"SLA (Service Level Agreement) deadlines are often measured in business days. Enter the ticket date and SLA period to find the due date."},
      {q:"How are working days counted in Malaysia?",a:"In Malaysia, working days are Mon–Fri for most sectors. However, Kelantan, Terengganu, and Kedah have Fri–Sat weekends in some contexts."},
      {q:"What is a business day vs a calendar day?",a:"A calendar day counts all 7 days. A business day counts only Mon–Fri. Contract terms often specify which applies."},
      {q:"How do I calculate working hours between dates?",a:"This calculator returns working days. For working hours, multiply working days by your daily hours (e.g., 8 for a standard full-time role)."},
      {q:"How do I calculate a notice period?",a:"Enter your last working day start date and add the required notice period in working days to find the end date."},
      {q:"What is a half day counted as?",a:"For standard calculation purposes, half days are counted as 0.5 working days. This calculator counts in whole days."},
    ]
  },
  { id:"countdown", slug:"countdown-timer", name:"Countdown Timer", icon:"⏳", category:"datetime", global:true,
    desc:"Live real-time countdown to any future event or date",
    longDesc:"Live countdown in days, hours, minutes and seconds to any future date. For weddings, holidays, launches, and personal milestones.",
    keywords:["countdown timer","countdown to date","event countdown","days until"],
    faq:[
      {q:"How does a countdown timer work?",a:"The countdown calculates the difference between the target date and the current date/time, displaying remaining days, hours, minutes, and seconds in real time."},
      {q:"How many days until New Year?",a:"Set the date to January 1 of the next year and the countdown will show the live countdown in days, hours, minutes and seconds."},
      {q:"Can I use this for a wedding countdown?",a:"Yes. Enter your wedding date and the calculator displays a live countdown. Bookmark the page to check back anytime."},
      {q:"How many days until Christmas 2025?",a:"Enter December 25, 2025 into the countdown timer to see the live days, hours, minutes and seconds remaining."},
      {q:"How many days are in a year?",a:"A standard year has 365 days. A leap year has 366 days. The countdown handles leap years automatically."},
      {q:"What is the most popular countdown event?",a:"New Year's Eve, Christmas, Eid al-Fitr, Chinese New Year, and personal events like weddings and birthdays are the most common targets."},
      {q:"How do I calculate how many weeks until a date?",a:"The Date Difference Calculator shows exact weeks. The Countdown Timer shows a real-time breakdown in days, hours, minutes and seconds."},
      {q:"How many days until Hari Raya 2025?",a:"Hari Raya Aidilfitri date varies based on the Islamic lunar calendar. Set the confirmed date in this countdown for an accurate countdown."},
      {q:"Can I count down to a specific time?",a:"The current version counts down to midnight of the target date. Note the hours remaining displayed for time-of-day reference."},
      {q:"How many days until my birthday?",a:"Enter your next birthday date into the countdown timer to see how many days, hours, minutes and seconds remain."},
    ]
  },
  { id:"timezone", slug:"time-zone-converter", name:"Time Zone Converter", icon:"🌍", category:"datetime", global:true,
    desc:"Live world clock across 20+ global time zones",
    longDesc:"Live world clock converting time across 20+ time zones. Shows current time in major cities. Handles DST automatically.",
    keywords:["time zone converter","world clock","timezone calculator","UTC converter","GMT converter"],
    faq:[
      {q:"How do I convert time zones?",a:"Select your reference time zone. The world clock shows current time in all major cities simultaneously, updating every second."},
      {q:"What is UTC?",a:"UTC (Coordinated Universal Time) is the primary time standard. All time zones are expressed as UTC offsets (e.g., Malaysia is UTC+8)."},
      {q:"What is Daylight Saving Time (DST)?",a:"DST advances clocks 1 hour during summer in regions that observe it (USA, Europe, Australia). Malaysia, Singapore and Japan do NOT observe DST."},
      {q:"What time zone is Malaysia in?",a:"Malaysia Standard Time (MST) is UTC+8. It does not observe Daylight Saving Time, the same as Singapore (SGT) and China Standard Time (CST)."},
      {q:"What is the time difference between KL and London?",a:"Kuala Lumpur (UTC+8) is 8 hours ahead of London (UTC+0 GMT). During UK Summer Time (BST, UTC+1), the difference is 7 hours."},
      {q:"How many time zones does the USA have?",a:"The continental US has 4 time zones: Eastern (UTC−5), Central (UTC−6), Mountain (UTC−7), Pacific (UTC−8). Alaska and Hawaii add two more."},
      {q:"What is IST (Indian Standard Time)?",a:"India Standard Time is UTC+5:30. India uses a single time zone for the entire country and does not observe Daylight Saving Time."},
      {q:"How do I schedule an international meeting?",a:"Use this Time Zone Converter to find overlapping business hours. 8–9 AM US East Coast is often best for US/Europe/Asia overlap."},
      {q:"What time zone is used for international flights?",a:"Aviation uses UTC (Zulu time) for all scheduling. Flight times shown in booking systems are in local time of departure and arrival cities."},
      {q:"What is GMT?",a:"GMT (Greenwich Mean Time) is practically identical to UTC but is a historical standard. UTC is the modern successor used in computing and aviation."},
    ]
  },
  { id:"public-holiday", slug:"public-holiday-calendar", name:"Public Holiday Calendar", icon:"📋", category:"datetime", global:true,
    desc:"Official holidays by country & year with long weekend highlights",
    longDesc:"View official public holidays for Malaysia, Singapore, UK, USA and Australia for 2024–2026. Highlights long weekends and bridge day opportunities.",
    keywords:["public holiday calendar","malaysia public holidays 2025","singapore public holidays","uk bank holidays","federal holidays usa"],
    faq:[
      {q:"What are the national public holidays in Malaysia?",a:"Malaysia has 12 federal public holidays including New Year's Day, Chinese New Year (2 days), Hari Raya Puasa (2 days), Wesak Day, Merdeka Day, Malaysia Day, Deepavali, and Christmas."},
      {q:"How many public holidays does Malaysia have per year?",a:"Malaysia has 12 federal public holidays plus additional state-level holidays. Total holidays vary by state: Selangor ~16, Kelantan ~18."},
      {q:"What is a gazetted public holiday?",a:"A gazetted holiday is officially declared under the Holidays Act 1951. Employees are entitled to these days off at full pay, or overtime pay if required to work."},
      {q:"What are the public holidays in Singapore?",a:"Singapore has 11 public holidays: New Year's Day, Chinese New Year (2 days), Good Friday, Labour Day, Vesak Day, Hari Raya Puasa, National Day, Hari Raya Haji, Deepavali, and Christmas."},
      {q:"How many public holidays are there in the UK?",a:"England and Wales have 8 bank holidays. Scotland has 9. Northern Ireland has 10. These include New Year, Easter, May Bank Holiday, Christmas, and Boxing Day."},
      {q:"What happens when a holiday falls on a weekend?",a:"In Malaysia, if a public holiday falls on a Sunday, the following Monday is declared a replacement holiday."},
      {q:"Are public holidays paid in Malaysia?",a:"Yes. Under the Employment Act 1955, employees are entitled to paid leave on all 11 gazetted public holidays per year."},
      {q:"How do Islamic holidays affect Malaysian dates?",a:"Islamic holidays (Hari Raya Puasa, Hari Raya Haji, Nuzul Quran, Maulidur Rasul) shift earlier by approximately 11 days each year following the lunar Hijri calendar."},
      {q:"Do state holidays differ across Malaysia?",a:"Yes. Each state has additional holidays for the Sultan's birthday, state founder's day, and local religious observances."},
      {q:"How can I plan around public holidays?",a:"Use this calendar alongside the Long Weekend Planner to identify bridge days and optimal annual leave timing for extended breaks."},
    ]
  },
  { id:"long-weekend", slug:"long-weekend-planner", name:"Long Weekend Planner", icon:"🏖️", category:"datetime", global:true,
    desc:"Find bridge holidays & extended weekend opportunities",
    longDesc:"Identify every long weekend and bridge day opportunity. Shows when 1–2 days leave creates a 4–5 day break.",
    keywords:["long weekend planner","bridge holiday","malaysia long weekend 2025","extended weekend","long weekend 2025"],
    faq:[
      {q:"What is a long weekend?",a:"A long weekend occurs when a public holiday falls on a Friday or Monday (or adjacent to a weekend), creating 3 or more consecutive days off."},
      {q:"What is a bridge day?",a:"A bridge day is a working day between a public holiday and a weekend. Taking leave on that day creates a 4+ day mini-break without using many leave days."},
      {q:"How many long weekends in Malaysia 2025?",a:"Malaysia typically has 4–7 long weekends per year depending on when public holidays fall. Use this planner to see exact dates."},
      {q:"How do I plan 4-day weekends with minimum leave?",a:"A public holiday on Thursday + 1 day leave on Friday = 4-day weekend. A holiday on Tuesday + Monday leave = 4-day weekend. This planner highlights all such opportunities."},
      {q:"What months have the most Malaysian public holidays?",a:"January–February (Chinese New Year), April–May (Hari Raya Puasa), and August (Merdeka) tend to cluster the most public holidays."},
      {q:"How is this different from the Public Holiday Calendar?",a:"The Public Holiday Calendar lists all holidays. This planner specifically identifies which ones create extended weekend opportunities and shows the bridge day strategy."},
      {q:"What is the best month to take a holiday in Malaysia?",a:"March–April and October–November generally have the most long weekend opportunities. School holidays in June and December are popular family travel periods."},
      {q:"Can I plan 4-day weekends?",a:"Yes. A holiday on Monday or Friday creates a 3-day weekend. A Tuesday or Thursday holiday with one bridge leave day creates a 4-day weekend."},
      {q:"How do I find long weekends in other countries?",a:"Select your country in this planner. The tool loads official public holidays and identifies all long weekend opportunities for your selected year."},
      {q:"Can I export the long weekend plan?",a:"Results can be copied from the tool. Future updates will support calendar export (.ics) for Google Calendar and Outlook integration."},
    ]
  },
  { id:"leave-optimizer", slug:"annual-leave-optimizer", name:"Annual Leave Optimizer", icon:"✈️", category:"datetime", global:true,
    desc:"Maximise days off with strategic leave placement",
    longDesc:"Optimise annual leave by ranking bridge day opportunities by days-off-per-leave-day ratio. Maximise total days off from limited annual leave entitlement.",
    keywords:["annual leave optimizer","leave planner","maximize annual leave","leave planning","smart leave","holiday optimizer"],
    faq:[
      {q:"What is annual leave optimization?",a:"Strategically placing leave days around public holidays and weekends to maximize total days off while using the fewest leave days."},
      {q:"How many days off can I get with 20 days leave?",a:"With 20 days strategically placed around Malaysia's public holidays and weekends, you can potentially create 40–50 total days off."},
      {q:"What is a leave bridge strategy?",a:"Taking 1–2 days annual leave between a public holiday and a weekend to create an extended break of 4–5 days using only 1–2 leave days."},
      {q:"How far in advance should I plan my leave?",a:"Plan at least 3–6 months ahead for popular periods like school holidays, Hari Raya, and Christmas. Submit early as popular dates fill up quickly."},
      {q:"How many days annual leave is standard in Malaysia?",a:"Under the Employment Act: 8 days for <2 years service, 12 days for 2–5 years, 16 days for >5 years. Most professional roles offer 14–21 days."},
      {q:"How does this tool calculate efficiency?",a:"Efficiency = Total days off gained ÷ Leave days used. A single leave day yielding 4 days off has 400% efficiency. Opportunities are ranked by this ratio."},
      {q:"Should I save leave for school holidays?",a:"If you have children, school holiday alignment matters. Consider reserving some leave days for June and December school breaks."},
      {q:"What is carry-forward leave?",a:"Many companies allow unused leave to carry forward to the next year, typically up to 50% of entitlement. Check your employment contract."},
      {q:"What is the best use of annual leave in Malaysia 2025?",a:"This optimizer calculates the highest-efficiency placements for any year, showing which 1–2 day bridges yield the most total days off."},
      {q:"Can the optimizer account for blackout dates?",a:"The current version shows all opportunities. Filter manually by removing dates that conflict with your company's blackout periods."},
    ]
  },
  { id:"currency", slug:"currency-converter", name:"Currency Converter", icon:"💱", category:"converters", global:true, badge:"LIVE",
    desc:"Live exchange rates — 36 world currencies",
    longDesc:"Live exchange rates from Open Exchange Rates API. 36 currencies with 1-hour refresh. Fallback rates when offline. Quick comparison table of 15 major currencies.",
    keywords:["currency converter","exchange rate calculator","usd to myr","sgd to myr","forex calculator","live exchange rates"],
    faq:[
      {q:"How often are exchange rates updated?",a:"Exchange rates are fetched from Open Exchange Rates API and cached for 1 hour. The last update timestamp is displayed below the result."},
      {q:"Which currencies are supported?",a:"36 world currencies including USD, EUR, GBP, MYR, SGD, JPY, AUD, CAD, CHF, CNY, HKD, INR, KRW, THB, IDR, PHP, VND, AED, SAR, QAR, KWD and more."},
      {q:"How accurate are the exchange rates?",a:"Rates reflect mid-market rates from a professional FX provider. Bank rates differ by 1–3% due to their spread and fees."},
      {q:"What is a mid-market exchange rate?",a:"The midpoint between buy and sell rates in global currency markets — the fairest rate, as shown by Google and XE.com."},
      {q:"Why is my bank rate different?",a:"Banks add a margin (spread) of 1–5% over the mid-market rate as their profit."},
      {q:"What is USD to MYR today?",a:"The live rate is shown when you click Get Live Rate. USD/MYR fluctuates daily based on market forces."},
      {q:"How do I convert EUR to MYR?",a:"Select EUR as From and MYR as To, enter your amount, and click Get Live Rate for the current conversion."},
      {q:"What is the SGD to MYR exchange rate?",a:"Historically ~3.3–3.4. Use this converter for the live rate updated hourly."},
      {q:"Does this calculator work offline?",a:"When live data is unavailable, approximate fallback rates are used with a warning shown. Always use live mode for accurate conversions."},
      {q:"What is a cross rate?",a:"A rate between two currencies where neither is USD, e.g. EUR/MYR = EUR/USD × USD/MYR."},
    ]
  },
  { id:"length", slug:"length-converter", name:"Length Converter", icon:"📏", category:"converters", global:true,
    desc:"Metric, imperial & nautical length units",
    longDesc:"Convert between mm, cm, m, km, inches, feet, yards, miles and nautical miles instantly.",
    keywords:["length converter","unit converter","meters to feet","km to miles","cm to inches"],
    faq:[
      {q:"How do I convert metres to feet?",a:"1 metre = 3.28084 feet. Multiply metres by 3.28084 to get feet."},
      {q:"How many centimetres in an inch?",a:"1 inch = 2.54 centimetres exactly. So 12 inches (1 foot) = 30.48 cm."},
      {q:"How do I convert km to miles?",a:"1 km = 0.621371 miles. For a quick estimate, multiply by 0.6 (about 4% underestimate)."},
      {q:"What is a nautical mile?",a:"A nautical mile = 1,852 metres or 1.15078 statute miles. Used in maritime and aviation navigation."},
      {q:"How do I convert height from cm to feet and inches?",a:"Divide cm by 30.48 for feet (whole number), then multiply the decimal remainder by 12 for inches. E.g., 170cm = 5 feet 6.9 inches."},
      {q:"How many mm in a cm?",a:"There are exactly 10 millimetres in 1 centimetre. 100cm = 1 metre. 1000mm = 1 metre."},
      {q:"What unit does the USA use for length?",a:"The USA primarily uses the imperial system: inches, feet, yards, and miles. Scientific fields use metric (SI) units globally."},
      {q:"How do I convert yards to metres?",a:"1 yard = 0.9144 metres exactly. Multiply yards by 0.9144 to convert to metres."},
      {q:"What is the difference between UK and US miles?",a:"The statute mile (1,609.344m) is used in both the UK and USA. The nautical mile (1,852m) is different and used only in navigation."},
      {q:"What is a light-year?",a:"A light-year is the distance light travels in one year: approximately 9.461 × 10^15 metres or about 5.879 trillion miles."},
    ]
  },
  { id:"weight", slug:"weight-converter", name:"Weight Converter", icon:"⚖️", category:"converters", global:true,
    desc:"kg, lbs, stones, grams, ounces & more",
    longDesc:"Convert between milligrams, grams, kilograms, metric tonnes, ounces, pounds and stones instantly.",
    keywords:["weight converter","kg to lbs","lbs to kg","grams to ounces","weight unit converter"],
    faq:[
      {q:"How do I convert kg to lbs?",a:"1 kg = 2.20462 lbs. Multiply kilograms by 2.20462 to get pounds. For quick mental math, multiply by 2.2."},
      {q:"How do I convert lbs to kg?",a:"1 lb = 0.453592 kg. Divide pounds by 2.205 to approximate. Use this converter for exact values."},
      {q:"What is a stone in kg?",a:"1 stone = 14 pounds = 6.35029 kg. The stone is used mainly in the UK and Ireland for body weight."},
      {q:"How many grams in an ounce?",a:"1 ounce = 28.3495 grams. For cooking, 1 ounce ≈ 28g is sufficient precision."},
      {q:"What is the difference between weight and mass?",a:"Mass is the amount of matter (kg). Weight is the force of gravity on that mass (Newtons). In everyday use, 'weight' typically means mass."},
      {q:"How do I convert metric tons to kg?",a:"1 metric tonne = 1,000 kg. Not to be confused with the US short ton (907.185 kg) or the UK long ton (1,016.05 kg)."},
      {q:"What is the difference between troy ounce and regular ounce?",a:"A troy ounce (31.1035g) is used for precious metals. A regular ounce (28.3495g) is used for everything else."},
      {q:"How many kg is 100 lbs?",a:"100 lbs = 45.3592 kg. Enter 100 lbs in this converter to see all equivalent values."},
      {q:"What is milligrams used for?",a:"Milligrams (0.001g) measure medicine dosages, vitamins, minerals, and very small quantities in chemistry and food labelling."},
      {q:"How do pharmacies measure medicine weight?",a:"Medicines are measured in milligrams (mg) and micrograms (mcg/µg). 1 mg = 1,000 mcg. Always follow prescribed dosages precisely."},
    ]
  },
  { id:"temperature", slug:"temperature-converter", name:"Temperature Converter", icon:"🌡️", category:"converters", global:true,
    desc:"Celsius, Fahrenheit & Kelvin converter",
    longDesc:"Convert between Celsius, Fahrenheit and Kelvin. Shows all three scales simultaneously with any input.",
    keywords:["temperature converter","celsius to fahrenheit","fahrenheit to celsius","kelvin converter"],
    faq:[
      {q:"How do you convert Celsius to Fahrenheit?",a:"°F = (°C × 9/5) + 32. For example, 25°C = (25 × 1.8) + 32 = 77°F."},
      {q:"How do you convert Fahrenheit to Celsius?",a:"°C = (°F − 32) × 5/9. For example, 98.6°F = (98.6 − 32) × 5/9 = 37°C (normal body temperature)."},
      {q:"What is 0 degrees Celsius in Fahrenheit?",a:"0°C = 32°F (the freezing point of water). 100°C = 212°F (the boiling point at sea level)."},
      {q:"What is absolute zero in Celsius?",a:"Absolute zero is −273.15°C (or 0 Kelvin) — the theoretical lowest possible temperature where all molecular motion stops."},
      {q:"What is normal body temperature?",a:"Normal human body temperature is 37°C (98.6°F). A fever is typically defined as above 38°C (100.4°F)."},
      {q:"What temperature does water boil and freeze?",a:"Water freezes at 0°C (32°F) and boils at 100°C (212°F) at sea level. Boiling point decreases at high altitudes."},
      {q:"What is the Kelvin scale used for?",a:"Kelvin is the SI unit used in science and physics. Unlike Celsius and Fahrenheit, Kelvin has no negative values — 0K is absolute zero."},
      {q:"What is room temperature in Celsius?",a:"Room temperature is typically 20–22°C (68–72°F). In scientific contexts, standard room temperature is defined as 25°C (77°F)."},
      {q:"What is Malaysia's average temperature?",a:"Malaysia has a tropical climate with average temperatures of 27–30°C (80–86°F) year-round. The Cameron Highlands are cooler at 12–25°C."},
      {q:"What is the hottest temperature ever recorded?",a:"The highest reliably recorded temperature was 56.7°C (134°F) at Furnace Creek, Death Valley, USA in 1913."},
    ]
  },
  { id:"data", slug:"data-storage-converter", name:"Data Storage Converter", icon:"💾", category:"converters", global:true,
    desc:"Bytes, KB, MB, GB, TB & PB converter",
    longDesc:"Convert between bytes, kilobytes, megabytes, gigabytes, terabytes and petabytes instantly.",
    keywords:["data storage converter","bytes to mb","gb to tb","file size converter","digital storage units"],
    faq:[
      {q:"How many bytes are in a megabyte?",a:"1 MB = 1,048,576 bytes (binary, base-2) used by operating systems, or 1,000,000 bytes (decimal) used by storage manufacturers."},
      {q:"How many GB in a TB?",a:"1 TB = 1,024 GB in binary (used by OS), or 1,000 GB in decimal (used on hard drive boxes). This is why a 1TB drive shows as ~931 GB on your computer."},
      {q:"How big is a typical movie file?",a:"A 1080p HD movie: 4–8 GB. A 4K HDR movie: 20–80 GB. A SD 480p movie: 0.7–1.5 GB. Streaming compresses these significantly."},
      {q:"How many photos can a 256GB phone hold?",a:"A 12MP photo is approximately 3–5 MB. A 256 GB phone can hold approximately 50,000–85,000 standard photos."},
      {q:"What is bandwidth vs storage?",a:"Storage (GB, TB) measures how much data you can hold. Bandwidth (Mbps, Gbps) measures how fast data transfers over a network."},
      {q:"How fast is 1 Gbps internet?",a:"1 Gbps = 1,000 Mbps = 125 MB/s theoretical maximum. In practice, 600–900 Mbps is typical real-world speed."},
      {q:"What is a petabyte used for?",a:"1 petabyte = 1,024 TB. Petabytes are used to describe large-scale data centre storage and global internet traffic."},
      {q:"How much data does a 4K video use?",a:"Streaming 4K Netflix uses approximately 7 GB/hour. 4K YouTube uses 5–17 GB/hour depending on HDR and frame rate settings."},
      {q:"What is the difference between MB and MiB?",a:"MB (megabyte) can mean 10^6 or 2^20 bytes depending on context. MiB (mebibyte) is precisely 2^20 = 1,048,576 bytes."},
      {q:"What is the largest unit of data storage?",a:"Common units: KB → MB → GB → TB → PB (petabyte) → EB (exabyte) → ZB (zettabyte) → YB (yottabyte)."},
    ]
  },
  { id:"speed", slug:"speed-converter", name:"Speed Converter", icon:"🏎️", category:"converters", global:true,
    desc:"km/h, mph, m/s, knots & ft/s converter",
    longDesc:"Convert between metres per second, kilometres per hour, miles per hour, knots and feet per second instantly.",
    keywords:["speed converter","kmh to mph","mph to kmh","knots converter","speed unit converter"],
    faq:[
      {q:"How do I convert km/h to mph?",a:"Divide km/h by 1.60934. For quick mental math: mph ≈ km/h × 0.62. E.g., 100 km/h = 62.1 mph."},
      {q:"How do I convert mph to km/h?",a:"Multiply mph by 1.60934. E.g., 60 mph × 1.60934 = 96.56 km/h."},
      {q:"What is a knot in km/h?",a:"1 knot = 1.852 km/h. Knots are used in maritime and aviation. A ship at 20 knots moves at 37 km/h."},
      {q:"How fast is Mach 1?",a:"Mach 1 (speed of sound) ≈ 340 m/s = 1,225 km/h = 761 mph at sea level and 15°C."},
      {q:"What is the average human walking speed?",a:"Average walking speed is 4–5 km/h (2.5–3.1 mph). Jogging is 8–12 km/h; running is 12–20 km/h."},
      {q:"How fast does commercial aircraft fly?",a:"Commercial jets cruise at 800–920 km/h (500–570 mph) at altitude."},
      {q:"What is the speed limit in Malaysia?",a:"Malaysia speed limits: 110 km/h on highways, 90 km/h on main roads, 60 km/h in urban areas, 30–40 km/h in school zones."},
      {q:"How do I convert m/s to km/h?",a:"Multiply m/s by 3.6. E.g., 10 m/s × 3.6 = 36 km/h. This is because 1 km = 1,000 m and 1 hour = 3,600 seconds."},
      {q:"What is the speed of light in km/h?",a:"The speed of light = 299,792,458 m/s ≈ 1.079 billion km/h. Nothing with mass can reach this speed."},
      {q:"What is terminal velocity?",a:"Terminal velocity is the maximum speed a falling object reaches when drag equals gravity. For a skydiver in freefall it is approximately 195 km/h."},
    ]
  },
  { id:"cooking", slug:"cooking-units-converter", name:"Cooking Units Converter", icon:"🍳", category:"converters", global:true,
    desc:"Cups, tablespoons, teaspoons, ml, litres & more",
    longDesc:"Convert between all cooking measurement units: ml, litres, teaspoons, tablespoons, cups, fluid ounces, pints, quarts and gallons.",
    keywords:["cooking converter","cups to ml","tablespoons to cups","cooking measurements","kitchen unit converter"],
    faq:[
      {q:"How many tablespoons in a cup?",a:"1 US cup = 16 tablespoons = 48 teaspoons = 240 ml."},
      {q:"How many ml in a tablespoon?",a:"1 tablespoon = 14.787 ml (US). In metric countries, 1 tablespoon is often rounded to 15 ml for cooking."},
      {q:"How many teaspoons in a tablespoon?",a:"1 tablespoon = 3 teaspoons. This applies in both US and metric measurement systems."},
      {q:"How do I convert cups to grams?",a:"Cups to grams depends on the ingredient. 1 cup flour ≈ 120g. 1 cup sugar ≈ 200g. 1 cup butter = 227g. 1 cup water = 240g."},
      {q:"What is a fluid ounce?",a:"1 US fluid ounce = 29.574 ml. 1 UK fluid ounce = 28.413 ml. This converter uses the US fluid ounce."},
      {q:"How many cups in a litre?",a:"1 litre = 4.227 US cups, or approximately 4 cups for cooking purposes."},
      {q:"How do I halve a recipe?",a:"Halve all ingredients proportionally. Use this converter to recalculate cup/tbsp/tsp amounts. E.g., 1/3 cup halved ≈ 2 tbsp + 2 tsp."},
      {q:"What is a metric cup?",a:"A metric cup = 250 ml, used in Australia, Canada, and New Zealand. A US cup = 240 ml. The 10ml difference matters for precise baking."},
      {q:"How many ml is a pint?",a:"1 US pint = 473.176 ml. 1 UK (imperial) pint = 568.261 ml. The UK pint is about 20% larger than the US pint."},
      {q:"Why do US and UK measurements differ?",a:"The US retained colonial measurements when they diverged from British units in the 19th century. The UK later adopted metric while the US did not."},
    ]
  },
  { id:"discount", slug:"discount-calculator", name:"Discount Calculator", icon:"🏷️", category:"daily", global:true,
    desc:"Sale price, savings amount & discount percentage",
    longDesc:"Instantly calculate sale price, savings amount and effective discount percentage. Quick-select buttons for common discounts.",
    keywords:["discount calculator","sale price calculator","percentage off","how much is 20 off","savings calculator"],
    faq:[
      {q:"How do I calculate a discount percentage?",a:"Discount % = ((Original Price − Sale Price) / Original Price) × 100."},
      {q:"How do I calculate 30% off a price?",a:"Sale price = Original × 0.70. For RM199, a 30% discount gives RM199 × 0.70 = RM139.30, saving RM59.70."},
      {q:"How do I stack multiple discounts?",a:"Stacked discounts are multiplicative, not additive. A 20% then 10% discount = 1 − (0.8 × 0.9) = 28% total, not 30%."},
      {q:"How do I find the original price before discount?",a:"Original Price = Sale Price / (1 − Discount%). E.g., if a 20% discounted price is RM80: RM80 / 0.8 = RM100."},
      {q:"What is a markdown vs markup?",a:"Markdown reduces from retail price. Markup increases from cost. This calculator handles percentage-off discounts."},
      {q:"How do I calculate tax after discount?",a:"Apply discount first to get the discounted price, then apply tax: Discounted Price × (1 + tax rate)."},
      {q:"What is a clearance sale discount?",a:"Typically 30–80% off retail. Retailers use clearance sales to clear excess inventory at end of season."},
      {q:"How do I calculate savings in percentage?",a:"Savings % = (Amount Saved / Original Price) × 100."},
      {q:"Is a higher discount always better?",a:"Not always. A 50% discount on an overpriced item may still cost more than a 10% discount on a fairly priced one."},
      {q:"What is the difference between a price-off and percentage-off?",a:"A fixed price-off (e.g. RM20 off) reduces by a set amount. A percentage-off (e.g. 10%) reduces proportionally."},
    ]
  },
  { id:"tip", slug:"tip-calculator", name:"Tip & Bill Splitter", icon:"🍽️", category:"daily", global:true,
    desc:"Calculate tip amount and split bill equally",
    longDesc:"Calculate tip amount, total bill, and per-person share for any number of diners. Quick-select tip percentages.",
    keywords:["tip calculator","bill splitter","restaurant calculator","how much to tip","split bill calculator"],
    faq:[
      {q:"How much should I tip?",a:"Tipping customs vary. In the US, 15–20% is standard. In Malaysia, service charge is usually included (10%). In Japan, tipping is not customary."},
      {q:"How do I calculate a 15% tip?",a:"Multiply the bill by 0.15. On RM200 bill, a 15% tip = RM30, making the total RM230."},
      {q:"Should I tip on pre-tax or post-tax amount?",a:"In the US, most tip on the pre-tax bill. In other countries, tipping on the total displayed is standard."},
      {q:"What is a service charge?",a:"A service charge is a mandatory addition (e.g., 10% in Malaysia) pre-added by the restaurant. Unlike a tip, it may not go directly to the server."},
      {q:"Is it rude not to tip?",a:"This depends on local customs. In North America and some European countries, not tipping is considered rude. In East Asia, tipping is often unnecessary or even declined."},
      {q:"How do I split a bill unevenly?",a:"This calculator provides the equal split with tip. For unequal splits, use the per-person amount and adjust manually for individual items."},
      {q:"Should I tip on a buffet?",a:"A smaller tip of 5–10% is common for buffet service where staff still bring drinks and clear plates."},
      {q:"What is the GST/SST tip rule in Malaysia?",a:"Many Malaysian restaurants add 10% service charge + 6% SST. Check if service charge is already included before adding an extra tip."},
      {q:"How do I tip with multiple payment methods?",a:"Calculate the total per person using this calculator, then each person pays their share via whatever method they choose."},
      {q:"What is an appropriate tip for food delivery?",a:"A tip of RM2–5 per delivery is considerate for food delivery riders in Malaysia. In the US, 10–20% of the order value is standard."},
    ]
  },
  { id:"fuel", slug:"fuel-cost-calculator", name:"Fuel Cost Calculator", icon:"⛽", category:"daily", global:true,
    desc:"Trip fuel cost by distance, L/100km & price per litre",
    longDesc:"Calculate fuel cost for road trips from distance, consumption, and fuel price. Shows litres needed and cost per 100km.",
    keywords:["fuel cost calculator","petrol cost calculator","road trip calculator","fuel consumption calculator"],
    faq:[
      {q:"How is fuel cost calculated?",a:"Fuel cost = (Distance ÷ 100) × Fuel consumption (L/100km) × Fuel price per litre."},
      {q:"What is the average fuel consumption of a car?",a:"Most modern sedans consume 7–12 L/100km. SUVs use 9–15 L/100km. Hybrids can achieve 4–6 L/100km."},
      {q:"What is the fuel price in Malaysia?",a:"RON 95 petrol in Malaysia is regulated at RM2.05/litre for eligible vehicles (as of 2024). RON 97 and diesel are market-priced."},
      {q:"How do I convert MPG to L/100km?",a:"L/100km = 235.21 ÷ MPG. For example, 35 MPG = 235.21 ÷ 35 = 6.72 L/100km."},
      {q:"How does driving speed affect fuel consumption?",a:"Fuel efficiency peaks around 80–90 km/h for most vehicles. Highway speeds above 110 km/h significantly increase fuel use due to aerodynamic drag."},
      {q:"How much does a KL to Singapore trip cost in fuel?",a:"The KL–Singapore distance is approximately 350 km. At 8 L/100km and RM2.05/litre, fuel cost is about RM57.40 one way."},
      {q:"How do I reduce fuel costs?",a:"Drive at steady speeds, maintain correct tyre pressure, avoid excessive air-conditioning, and reduce unnecessary weight in the vehicle."},
      {q:"Does carrying extra weight increase fuel use?",a:"Yes. Every 50 kg of extra weight increases fuel consumption by approximately 1–2%."},
      {q:"How is fuel efficiency measured in different countries?",a:"The US uses MPG (miles per gallon). Most countries use L/100km. UK uses both. This calculator uses L/100km as the standard unit."},
      {q:"What is idling fuel consumption?",a:"A typical car idles at 0.5–1 litre per hour. Turning off your engine rather than idling for more than 1 minute saves fuel."},
    ]
  },
  { id:"electricity", slug:"electricity-bill-calculator", name:"Electricity Bill Calculator", icon:"⚡", category:"daily", global:true,
    desc:"Monthly electricity cost — TNB tiered or custom rate",
    longDesc:"Estimate electricity bills using Malaysia TNB tiered tariff or a custom rate for any country. Daily average and monthly cost.",
    keywords:["electricity bill calculator","electricity cost calculator","tnb calculator","kwh calculator","power bill"],
    faq:[
      {q:"How is the electricity bill calculated in Malaysia?",a:"Malaysia uses TNB's tiered tariff: 21.8 sen/kWh for first 200kWh, 33.4 sen for 201–300kWh, 51.6 sen for 301–600kWh, and 54.6 sen above 600kWh."},
      {q:"What is a kWh?",a:"A kilowatt-hour (kWh) is the energy used by a 1,000-watt (1 kW) device running for one hour. Most appliances are rated in watts; multiply by hours to get watt-hours, then divide by 1,000."},
      {q:"How do I calculate my electricity usage?",a:"Multiply appliance wattage by hours of use per day, then by 30 for monthly kWh. E.g., a 100W light bulb used 8 hours/day = 0.8 kWh/day = 24 kWh/month."},
      {q:"What is the average household electricity usage in Malaysia?",a:"A typical Malaysian household uses 300–600 kWh per month. Heavily air-conditioned homes can exceed 1,000 kWh."},
      {q:"How do I use a custom rate for other countries?",a:"Select 'Custom rate' and enter your local utility rate per kWh. This applies a flat rate across all usage."},
      {q:"How do I reduce my electricity bill?",a:"Set air-con to 24–26°C, use LED lighting, unplug devices on standby, and use inverter appliances which adjust power based on demand."},
      {q:"What is TNB's fuel cost adjustment?",a:"TNB's tariff may include an Imbalance Cost Pass-Through (ICPT) surcharge or rebate depending on fuel prices. The base tiered rates are used in this calculator."},
      {q:"Does electricity SST apply in Malaysia?",a:"Electricity for domestic use below RM100/month is SST-exempt. Above RM100/month, 6% SST applies to the excess."},
      {q:"What appliances use the most electricity?",a:"Air conditioning (1,000–2,500W), water heaters (3,000–4,500W), washing machines (500–1,000W), and refrigerators (100–400W) are the biggest consumers."},
      {q:"What is the custom rate for Singapore?",a:"Singapore's SP Group residential tariff is approximately SGD 0.2898/kWh (as of 2024, Q4). Rates vary quarterly."},
    ]
  },
  { id:"password", slug:"password-generator", name:"Password Generator", icon:"🔐", category:"daily", global:true,
    desc:"Cryptographically secure passwords — nothing sent to any server",
    longDesc:"Generate strong passwords using the Web Crypto API. Length 8–64, custom character sets. Nothing sent to any server. Fully client-side.",
    keywords:["password generator","secure password generator","random password","strong password maker"],
    faq:[
      {q:"How secure is this password generator?",a:"This generator uses the Web Cryptography API (crypto.getRandomValues()), which provides cryptographically strong random values certified for security applications."},
      {q:"What makes a password strong?",a:"A strong password has: minimum 12 characters, a mix of uppercase, lowercase, numbers and symbols, no dictionary words, and is unique to each account."},
      {q:"How long should my password be?",a:"Security experts recommend at least 16 characters. Each additional character exponentially increases the time required to crack it by brute force."},
      {q:"Is it safe to use an online password generator?",a:"This generator creates passwords entirely in your browser using JavaScript — no passwords are sent to any server, logged, or stored anywhere."},
      {q:"Should I use a password manager?",a:"Yes. A password manager (like Bitwarden, 1Password, or iCloud Keychain) stores unique, complex passwords for every site, so you only need to remember one master password."},
      {q:"What is entropy in password security?",a:"Entropy measures password randomness in bits. A 16-character password using all character types has ~95 bits of entropy — effectively uncrackable by brute force."},
      {q:"What are common password mistakes?",a:"Using personal information (birthdays, names), reusing passwords across sites, using simple substitutions (p@ssw0rd), and passwords under 12 characters."},
      {q:"What is two-factor authentication (2FA)?",a:"2FA adds a second verification step (usually a code from an authenticator app or SMS) after your password, significantly increasing account security."},
      {q:"How often should I change my passwords?",a:"Current NIST guidelines recommend changing passwords only when you suspect a breach, not on a fixed schedule, as frequent changes lead to weaker choices."},
      {q:"Can someone guess a randomly generated password?",a:"A 16-character random password with mixed characters has over 10^31 possible combinations — billions of years to crack even with supercomputers."},
    ]
  },
  { id:"percentage", slug:"percentage-calculator", name:"Percentage Calculator", icon:"%", category:"daily", global:true,
    desc:"X% of Y, percentage change & ratio in 3 modes",
    longDesc:"Three-mode: X% of Y, percentage change, and what % is X of Y. Instant results with clear labelling.",
    keywords:["percentage calculator","percent calculator","percentage change","what percent of"],
    faq:[
      {q:"How do I calculate 20% of 500?",a:"Multiply 500 by 0.20 to get 100. Or: 500 × 20 ÷ 100 = 100. Use 'X% of Y' mode."},
      {q:"How do I calculate percentage increase?",a:"% Increase = ((New Value − Old Value) / Old Value) × 100. Use 'Percentage Change' mode."},
      {q:"How do I find what percentage X is of Y?",a:"X is what % of Y = (X / Y) × 100. Use 'X is ?% of Y' mode."},
      {q:"How do I reverse a percentage increase?",a:"If a value increased by N%, the original = New Value / (1 + N/100). For a 20% increase to 120: 120 / 1.20 = 100."},
      {q:"How do I calculate GST/VAT from a price?",a:"If GST is 6%: Tax amount = Price × 0.06. Price before tax = Total / 1.06."},
      {q:"What is a percentage point vs a percentage?",a:"A percentage point is an absolute difference. If interest rises from 3% to 5%, it rose 2 percentage points, but 66.7% as a relative increase."},
      {q:"How do I calculate exam scores as percentages?",a:"Score % = (Marks Obtained / Total Marks) × 100. Enter marks as X and total as Y in 'X is ?% of Y' mode."},
      {q:"What is compound percentage growth?",a:"Compound growth applies percentage growth repeatedly. 10% growth for 3 years = 1.10 × 1.10 × 1.10 = 1.331, a total 33.1% increase."},
      {q:"How do I calculate a tip percentage?",a:"Tip % = (Tip Amount / Bill Amount) × 100. Use the Tip Calculator on this site for full bill-splitting."},
      {q:"How do I calculate the percentage difference between two numbers?",a:"% difference = |V1 − V2| / ((V1 + V2) / 2) × 100. Use 'Percentage Change' mode for directional change."},
    ]
  },
  { id:"moving-cost", slug:"moving-cost-estimator", name:"Moving Cost Estimator", icon:"📦", category:"daily", global:true,
    desc:"Relocation costs by home size, distance & service type",
    longDesc:"Estimate moving costs by home size, distance and service level. Currency-adjustable for international use.",
    keywords:["moving cost estimator","house moving calculator","relocation cost","how much does moving cost"],
    faq:[
      {q:"How much does it cost to move house?",a:"Moving costs depend on distance, volume, and service type. Local city moves typically cost RM300–1,500; interstate moves RM800–3,000+."},
      {q:"How do movers calculate cost?",a:"Most movers price based on volume (cubic feet/lorry trips), distance, number of workers, floor level, and whether packing services are included."},
      {q:"What does a full service move include?",a:"Full service: packing, wrapping, transport, unpacking, and sometimes storage. Full service costs 2–3× basic moving (transport + labour only)."},
      {q:"How do I save money on moving costs?",a:"Declutter before moving, move mid-week/month (lower demand), pack yourself, compare at least 3 quotes, and avoid peak holiday periods."},
      {q:"What is the average cost to move from KL to Penang?",a:"An interstate move from KL to Penang for a 3-bedroom house typically costs RM1,200–2,500 including transport and labour."},
      {q:"When is the cheapest time to hire movers?",a:"Mid-week (Tuesday–Thursday) and mid-month are typically 10–20% cheaper than weekends and month-end."},
      {q:"What insurance do I need when moving?",a:"Ask your mover if they carry goods-in-transit insurance. For valuable items, consider separate insurance as movers' liability is often limited."},
      {q:"How do I estimate the volume of my belongings?",a:"A furnished 3-bedroom house is approximately 800–1,200 cubic feet. A studio is 200–400 cubic feet."},
      {q:"How much should I tip movers?",a:"In Malaysia, RM10–20/worker for a half-day job; RM30–50/worker for a full stressful day."},
      {q:"What is the cost to move internationally?",a:"KL to Singapore: ~RM2,000–5,000 for a partial container. To Europe or USA: USD 3,000–8,000+ for a 20-foot container."},
    ]
  },
  { id:"cost-of-living", slug:"cost-of-living-calculator", name:"Cost of Living Calculator", icon:"🏙️", category:"daily", global:true,
    desc:"Compare living costs between 35 world cities",
    longDesc:"Compare cost of living in 35 major world cities. Shows relative housing, food and transport costs indexed to New York City. For relocation and salary planning.",
    keywords:["cost of living calculator","city comparison","cost of living comparison","relocation calculator"],
    faq:[
      {q:"What factors make up cost of living?",a:"Housing (rent/mortgage), food, transportation, utilities, healthcare, education, entertainment, and personal care costs in a given city."},
      {q:"How does Kuala Lumpur compare to Singapore?",a:"KL is roughly 40–50% cheaper than Singapore overall. Housing in Singapore is 3–4× more expensive; food and transport are also much higher."},
      {q:"What is the cost of living index?",a:"The Cost of Living Index compares expenses relative to New York City (index 100). A city with index 50 is 50% cheaper than NYC."},
      {q:"How much do I need to earn to live comfortably in KL?",a:"A comfortable single lifestyle in KL requires approximately RM4,000–6,000/month. A family of 4 with children in international school needs RM12,000–20,000+."},
      {q:"How much is rent in Kuala Lumpur?",a:"KL City Centre condos: RM2,000–5,000/month. Suburbs (PJ, Subang): RM1,200–2,500/month. More affordable areas: RM800–1,500/month."},
      {q:"Is London more expensive than New York?",a:"Overall, NYC is slightly more expensive, particularly for rent. However, UK healthcare is largely free through the NHS, significantly reducing total costs."},
      {q:"What is purchasing power parity (PPP)?",a:"PPP adjusts for differences in price levels between countries to compare real standards of living."},
      {q:"Which is the cheapest city in Southeast Asia?",a:"Based on Numbeo data, cities like Ho Chi Minh City, Jakarta, and Manila consistently rank as the most affordable in SEA."},
      {q:"How much does food cost per month in major cities?",a:"Groceries for one person: KL ~RM400–600, Singapore ~RM600–900, London ~£200–300, NYC ~$300–450."},
      {q:"How do I use this tool to plan relocation?",a:"Select your current city and target city. The tool shows index comparisons for housing, food, transport, and utilities to estimate the salary needed to maintain your lifestyle."},
    ]
  },
  { id:"bmi", slug:"bmi-calculator", name:"BMI Calculator", icon:"⚕️", category:"health", global:true,
    desc:"Body Mass Index with WHO weight classifications",
    longDesc:"Calculate BMI in metric or imperial. WHO classification with colour-coded result and healthy weight range.",
    keywords:["bmi calculator","body mass index","healthy weight calculator","bmi chart","bmi for women","bmi for men"],
    faq:[
      {q:"What is BMI?",a:"BMI (Body Mass Index) is calculated as weight (kg) divided by height squared (m²). A widely used screening tool to categorise weight status."},
      {q:"What is a healthy BMI range?",a:"WHO classifies BMI 18.5–24.9 as Normal Weight. Below 18.5 is Underweight, 25–29.9 is Overweight, and 30+ is Obese."},
      {q:"Is BMI accurate for everyone?",a:"BMI doesn't account for muscle mass, bone density, or ethnicity. Athletes may have high BMI despite low body fat."},
      {q:"What BMI is considered obese?",a:"BMI 30+ is Obese: Class I (30–34.9), Class II (35–39.9), or Class III (40+). Each carries progressively higher health risks."},
      {q:"What is the ideal BMI for Asians?",a:"WHO recommends lower thresholds for Asians: overweight is BMI ≥23, obese is ≥27.5, due to higher metabolic risk at lower BMI."},
      {q:"How is imperial BMI calculated?",a:"Imperial BMI = (weight in pounds × 703) ÷ (height in inches)²."},
      {q:"Does BMI differ for men and women?",a:"The formula is the same but interpretation differs. Women naturally have higher body fat % at the same BMI."},
      {q:"How can I lower my BMI?",a:"Reduce weight through a caloric deficit and increasing physical activity. Sustainable changes of 0.5–1 kg/week are recommended."},
      {q:"What is a healthy BMI for women?",a:"18.5–24.9 is the healthy range. Female athletes may exceed 25 due to muscle mass without excess fat."},
      {q:"Is BMI a good predictor of health?",a:"It's useful at population level but limited individually. Waist circumference and body fat % give a more complete picture."},
    ]
  },
  { id:"calories", slug:"calorie-calculator", name:"Calorie & TDEE Calculator", icon:"🥗", category:"health", global:true,
    desc:"Daily calorie needs, BMR & macro targets",
    longDesc:"TDEE and BMR using Mifflin-St Jeor. Targets for weight loss, maintenance, muscle gain plus macro breakdown.",
    keywords:["calorie calculator","tdee calculator","bmr calculator","macro calculator","calorie deficit"],
    faq:[
      {q:"What is TDEE?",a:"TDEE (Total Daily Energy Expenditure) is the total calories your body burns daily, including BMR plus activity."},
      {q:"How is BMR calculated?",a:"This calculator uses the Mifflin-St Jeor equation: BMR = 10×weight(kg) + 6.25×height(cm) − 5×age + 5 (men) or −161 (women)."},
      {q:"How many calories should I eat to lose weight?",a:"A deficit of 500 calories/day below TDEE typically produces ~0.5 kg of fat loss per week — a safe and sustainable rate."},
      {q:"What are macronutrients?",a:"Protein (4 kcal/g), carbohydrates (4 kcal/g), and fat (9 kcal/g). This calculator provides recommended macro targets based on TDEE."},
      {q:"What activity level should I choose?",a:"Sedentary = desk job. Light = exercise 1–3 days/week. Moderate = 3–5 days/week. Active = 6–7 days/week. Very Active = athlete or physical labour."},
      {q:"How much protein do I need daily?",a:"General recommendation: 1.6–2.2g protein per kg bodyweight for active individuals. Higher intakes support muscle retention during weight loss."},
      {q:"Does age affect calorie needs?",a:"Yes. BMR decreases approximately 2–3% per decade after age 20 due to decreased muscle mass and metabolic rate changes."},
      {q:"Are calorie calculators accurate?",a:"TDEE calculators provide estimates within ±10–15% for most people. Individual factors like genetics and hormones affect actual energy expenditure."},
      {q:"What is a caloric surplus?",a:"Eating more than TDEE is required for muscle gain. A modest surplus of 200–300 calories minimises fat gain while supporting muscle growth."},
      {q:"How many calories does exercise burn?",a:"Running burns ~8–10 kcal/min, walking ~3–5 kcal/min, depending on body weight and intensity."},
    ]
  },
  { id:"bodyfat", slug:"body-fat-calculator", name:"Body Fat Calculator", icon:"💪", category:"health", global:true,
    desc:"Body fat % via US Navy circumference method",
    longDesc:"Estimate body fat % using the US Navy circumference formula. Accurate to ±3–4% vs DEXA scans.",
    keywords:["body fat calculator","body fat percentage","navy body fat formula","bf percentage"],
    faq:[
      {q:"How is body fat percentage measured?",a:"Methods include DEXA scan (most accurate), hydrostatic weighing, skinfold calipers, BIA, and the US Navy circumference method used in this calculator."},
      {q:"What is a healthy body fat percentage?",a:"Men: essential 2–5%, athlete 6–13%, fitness 14–17%, acceptable 18–24%, obese 25%+. Women: essential 10–13%, athlete 14–20%, fitness 21–24%, acceptable 25–31%, obese 32%+."},
      {q:"How accurate is the Navy body fat formula?",a:"The US Navy method has accuracy of ±3–4% compared to DEXA scans. It is suitable for tracking changes over time."},
      {q:"What measurements are needed?",a:"Men need neck and waist circumference plus height. Women additionally need hip circumference. All measurements in centimetres."},
      {q:"Where do I measure waist circumference?",a:"Measure at the narrowest point for women (above navel), or at the navel level for men. Measure after exhaling normally."},
      {q:"Can body fat % be too low?",a:"Yes. Essential fat (below ~5% men, 13% women) is required for hormonal function and organ protection. Extremely low body fat causes serious health complications."},
      {q:"What is visceral fat?",a:"Visceral fat is stored around internal organs in the abdominal cavity. High visceral fat is linked to greater cardiovascular disease risk."},
      {q:"How do I reduce body fat percentage?",a:"Consistent caloric deficit, adequate protein (1.6–2.2g/kg), resistance training to preserve muscle, and patience — sustainable fat loss is 0.5–1%/month."},
      {q:"What is the difference between body fat and BMI?",a:"BMI estimates weight relative to height. Body fat % measures the actual proportion of fat in your body — a better indicator of metabolic health."},
      {q:"Does BMI tell you about body fat?",a:"BMI doesn't directly measure body fat. Two people with the same BMI can have very different body fat percentages, especially athletes vs sedentary individuals."},
    ]
  },
  { id:"ideal-weight", slug:"ideal-weight-calculator", name:"Ideal Weight Calculator", icon:"🎯", category:"health", global:true,
    desc:"Healthy weight range using 4 clinical formulas",
    longDesc:"Ideal body weight from four clinical formulas: Devine, Miller, Hamwi, and BMI-22. Side-by-side comparison.",
    keywords:["ideal weight calculator","healthy weight","target weight","devine formula"],
    faq:[
      {q:"What is the ideal weight for my height?",a:"Ideal weight varies by formula, gender, and frame size. This calculator shows four clinical formula results side by side."},
      {q:"What is the Devine formula?",a:"Devine (1974): Men = 50 + 2.3kg per inch over 5 feet. Women = 45.5 + 2.3kg per inch over 5 feet. Originally designed for medication dosing."},
      {q:"What is the Hamwi method?",a:"Hamwi (1964): Men = 48kg + 2.7kg per inch over 5 feet. Women = 45.4kg + 2.27kg per inch over 5 feet. Used clinically for nutritional assessment."},
      {q:"What is the Miller formula?",a:"Miller (1983): Men = 56.2 + 1.41kg per inch over 5 feet. Women = 53.1 + 1.36kg per inch over 5 feet. Tends to give slightly higher values than Devine."},
      {q:"Which ideal weight formula is most accurate?",a:"No single formula is definitively superior for individuals. The average of multiple formulas provides a reasonable target range."},
      {q:"Is there an ideal weight for athletes?",a:"Athletes may weigh more than standard formulas suggest due to muscle mass. Body composition (body fat %) is more relevant than scale weight for athletes."},
      {q:"Should I aim for the lowest ideal weight?",a:"No. Aim for the middle of your healthy weight range. Being at the very low end may not be sustainable and could compromise strength and energy."},
      {q:"Does age affect ideal weight?",a:"Most formulas don't factor in age. Some research suggests slightly higher body weight may be acceptable in older adults (65+) for overall health."},
      {q:"What is a healthy weight range for a 170cm woman?",a:"Using BMI 18.5–24.9: ideal weight for 170cm = 53.5–71.9kg. Devine formula gives 61.8kg."},
      {q:"How is ideal weight different from goal weight?",a:"Ideal weight is a health-based target. Goal weight is personal. Ensure your goal weight falls within the healthy BMI range for your height."},
    ]
  },
  { id:"water", slug:"water-intake-calculator", name:"Water Intake Calculator", icon:"💧", category:"health", global:true,
    desc:"Daily hydration goal by weight & activity",
    longDesc:"Optimal daily water intake from body weight, activity, and climate. In litres, ml, and glasses.",
    keywords:["water intake calculator","daily water intake","how much water to drink","hydration calculator"],
    faq:[
      {q:"How much water should I drink per day?",a:"A general guideline is 35ml per kg of body weight. A 70kg person needs approximately 2.45 litres daily, more if active or in a hot climate."},
      {q:"Does the 8 glasses a day rule hold?",a:"The '8×8' rule (eight 250ml glasses = 2 litres) is a rough guide but not scientifically precise. Actual needs vary by body weight, activity, and climate."},
      {q:"Does tea and coffee count toward water intake?",a:"Yes. While caffeinated drinks have mild diuretic effects, research shows coffee and tea still contribute positively to daily fluid intake."},
      {q:"Does food contribute to water intake?",a:"Yes. Fruits and vegetables (cucumber, watermelon, lettuce) are 90–95% water. Diet typically provides 20–30% of daily water needs."},
      {q:"How does activity level affect water needs?",a:"Add 500–1000ml for every hour of moderate exercise, more in hot weather or for intense activity."},
      {q:"What are signs of dehydration?",a:"Early signs: dark yellow urine, thirst, dry mouth. Moderate: headache, dizziness, fatigue. Severe dehydration requires immediate medical attention."},
      {q:"Can you drink too much water?",a:"Yes. Overhydration (hyponatremia) can occur if excessive water dilutes blood sodium levels. This is rare but can occur during endurance sports."},
      {q:"Does climate affect water needs?",a:"Hot and humid climates increase sweat rate. The calculator applies a 15% increase for hot climates to recommended daily intake."},
      {q:"How do I track water intake?",a:"Use a water bottle with volume markings, a hydration tracking app, or set hourly reminders. This calculator converts your daily goal to number of 250ml glasses."},
      {q:"Do I need more water when pregnant?",a:"Pregnant women need approximately 2.3 litres/day; breastfeeding women need 3.1 litres/day. Consult your healthcare provider for personalised guidance."},
    ]
  },
  { id:"rent-vs-buy", slug:"rent-vs-buy-calculator", name:"Rent vs Buy Calculator", icon:"🏡", category:"home", global:true,
    desc:"True long-term cost of renting vs buying property",
    longDesc:"Compare renting vs buying over 20–30 years including mortgage, opportunity cost, and appreciation.",
    keywords:["rent vs buy calculator","should i rent or buy","property calculator","buy or rent house"],
    faq:[
      {q:"Is it better to rent or buy a house?",a:"It depends on your financial situation, market conditions, and life plans. Buying builds equity but requires capital. Renting offers flexibility without large upfront costs."},
      {q:"What is the price-to-rent ratio?",a:"P/R ratio = Property Price / Annual Rent. Below 15 favours buying; 15–20 is neutral; above 20 favours renting. In Kuala Lumpur, P/R ratios are typically 25–35."},
      {q:"What hidden costs of buying are often overlooked?",a:"Stamp duty, legal fees, valuation fees, maintenance fees, sinking fund, property tax, renovation costs, and opportunity cost of the down payment."},
      {q:"How much down payment is required in Malaysia?",a:"Minimum 10% for the first two residential properties, 30% for the third and subsequent under Bank Negara Malaysia guidelines."},
      {q:"What is property appreciation?",a:"Property appreciation is the increase in property value over time. Malaysian residential property has historically appreciated 3–7% p.a. in key markets."},
      {q:"What break-even year means in rent vs buy?",a:"The year when cumulative buying costs (including equity built) equal cumulative renting costs. Buying typically becomes better after 7–10 years."},
      {q:"Does renting build wealth?",a:"Renting itself doesn't build wealth directly, but money saved vs buying (lower monthly cost, no down payment) can be invested to build wealth."},
      {q:"How does loan tenure affect the rent vs buy decision?",a:"Longer loan tenure = lower monthly cost but more total interest. Compare 20-year vs 30-year scenarios to find the optimal tenure."},
      {q:"What is RPGT in Malaysia?",a:"RPGT (Real Property Gains Tax) is taxed on property sale profits. Rates reduce with holding period: 30% if sold within 3 years, 0% after 5 years for Malaysian citizens."},
      {q:"What is the opportunity cost of a down payment?",a:"If your 10% down payment is RM50,000, that money invested at 8% returns could grow to over RM230,000 in 20 years — this is the opportunity cost of buying."},
    ]
  },
  { id:"renovation", slug:"renovation-budget-calculator", name:"Renovation Budget Calculator", icon:"🔨", category:"home", global:true,
    desc:"Cost estimate by floor area, grade & currency",
    longDesc:"Estimate renovation costs by sqft and grade (basic/mid/luxury). Currency-adjustable globally.",
    keywords:["renovation cost calculator","home renovation calculator","renovation budget","renovation cost per sqft"],
    faq:[
      {q:"How much does it cost to renovate a house in Malaysia?",a:"Renovation costs range from RM60–100/sqft for basic works, RM100–180/sqft for mid-range, and RM200–350+/sqft for luxury finishes in the Klang Valley."},
      {q:"What is included in basic renovation?",a:"Flooring, painting, basic kitchen cabinets, ceiling works, bathroom fittings, and electrical/plumbing updates without high-end materials."},
      {q:"How do I estimate renovation budget by room?",a:"Kitchen: RM15,000–50,000. Master bathroom: RM8,000–25,000. Living/dining: RM5,000–20,000. Each bedroom: RM3,000–10,000."},
      {q:"Should I get multiple renovation quotes?",a:"Yes. Get at least 3 quotes from different contractors. Significant price differences (>30%) may indicate varying material quality or scope."},
      {q:"What is the difference between an ID firm and a contractor?",a:"An ID firm provides design consultation, 3D planning, and project management. A direct contractor builds to your specifications. ID adds 20–40% cost but provides design expertise."},
      {q:"How long does a full home renovation take?",a:"A full renovation of a typical 3-bedroom terrace house takes 3–6 months depending on scope and contractor efficiency."},
      {q:"Does renovation require permit in Malaysia?",a:"Structural changes and works affecting the building exterior typically require local authority approval. Internal cosmetic works usually do not."},
      {q:"What renovation works have the best ROI?",a:"Kitchen and bathroom renovations consistently provide the best ROI when reselling. Curb appeal improvements and adding a bedroom also yield strong returns."},
      {q:"How do I finance a home renovation?",a:"Options include savings, personal loan (4–8% p.a.), home equity loan, renovation loan (some banks offer these), or BNPL renovation financing schemes."},
      {q:"What is the true cost including hidden costs?",a:"Add 10–15% contingency to any quote for unforeseen structural issues, material price changes, or design changes. Appliances, furniture, and curtains are typically separate."},
    ]
  },
  { id:"road-tax", slug:"road-tax-calculator-malaysia", name:"Road Tax Calculator", icon:"🚗", category:"home", global:false, tag:"MY",
    desc:"Malaysia vehicle road tax by engine capacity & vehicle type",
    longDesc:"Calculate Malaysia annual road tax per JPJ schedule for saloon and non-saloon vehicles.",
    keywords:["road tax calculator malaysia","cukai jalan","jpj road tax","vehicle road tax malaysia"],
    faq:[
      {q:"How is road tax calculated in Malaysia?",a:"Road tax is calculated based on the vehicle's engine cubic capacity (cc) and type (saloon vs non-saloon). Larger engines pay progressively higher rates."},
      {q:"What is the road tax for a 1500cc car?",a:"A 1500cc saloon pays RM90/year base road tax. Non-saloon vehicles of 1400–1600cc pay RM56."},
      {q:"Where do I pay road tax in Malaysia?",a:"Road tax can be renewed at JPJ offices, post offices, Pos Malaysia, MyEG portal (online), and selected banks."},
      {q:"Can I drive with expired road tax in Malaysia?",a:"No. Driving with expired road tax is illegal and carries fines of RM300–RM2,000 under the Road Transport Act 1987."},
      {q:"How long is Malaysia road tax valid?",a:"Road tax is typically renewed annually (1 year). 6-month periods may be available at JPJ offices."},
      {q:"Do electric vehicles pay road tax in Malaysia?",a:"EV road tax was revised in 2024. EVs above 75kW motor power are subject to road tax. Smaller EVs may qualify for reduced rates."},
      {q:"What is the road tax for a motorcycle?",a:"Motorcycle road tax starts from RM2/year for engines under 150cc and increases up to RM114/year for motorcycles above 500cc."},
      {q:"Is road tax included in Takaful/insurance?",a:"No. Road tax and car insurance/Takaful are separate payments. Many agents offer bundled renewal but payments go to different bodies (JPJ vs insurer)."},
      {q:"How do I calculate road tax for a Perodua Myvi?",a:"Perodua Myvi has a 1,300cc engine. As a saloon, road tax is RM70/year. Enter 1300cc and Saloon type in the calculator to confirm."},
      {q:"What is the road tax for a 2000cc SUV?",a:"A 2000cc non-saloon pays RM90 base road tax. For saloon at 2000cc: RM280 + (200 × RM0.50) = RM380/year."},
    ]
  },
];

export const TOOL_MAP = Object.fromEntries(TOOLS.map(t => [t.id, t]));
export const SLUG_MAP = Object.fromEntries(TOOLS.map(t => [t.slug, t]));
export const CATEGORIES: Record<string, { label: string; desc: string; color: string }> = {
  finance:    { label:"Finance",       desc:"Salary, tax, loans, investments and more",        color:"#22c55e" },
  datetime:   { label:"Date & Time",   desc:"Age, countdowns, holidays and leave planning",    color:"#3b82f6" },
  converters: { label:"Converters",    desc:"Currency, units and measurement conversions",     color:"#a855f7" },
  daily:      { label:"Daily Tools",   desc:"Discounts, fuel, electricity and everyday tools", color:"#f59e0b" },
  health:     { label:"Health",        desc:"BMI, calories, hydration and body composition",   color:"#ef4444" },
  home:       { label:"Home & Living", desc:"Property, renovation, moving and living costs",   color:"#06b6d4" },
};

export function getToolsByCategory(cat: string): Tool[] { return TOOLS.filter(t => t.category === cat); }
export function getRelatedTools(id: string, limit = 5): Tool[] {
  const tool = TOOL_MAP[id];
  if (!tool) return [];
  return TOOLS.filter(t => t.id !== id && t.category === tool.category).slice(0, limit);
}
